import type { Metadata, Viewport } from "next";
import { Inter, Instrument_Serif } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { ClientWrapper } from "@/components/layout/client-wrapper";
import { ScrollToTop } from "@/components/ui/scroll-to-top";
import { ThemeProvider } from "@/components/theme-provider";
import { JsonLd } from "@/components/seo/json-ld";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});

const instrumentSerif = Instrument_Serif({
    subsets: ["latin"],
    weight: "400",
    style: ["normal", "italic"],
    variable: "--font-instrument",
});

export const metadata: Metadata = {
    metadataBase: new URL("https://adityaks-portfolio.vercel.app"),
    title: {
        default:
            "Aditya Kumar | Frontend Developer & React Specialist | India",
        template: "%s | Aditya Kumar",
    },
    description:
        "Frontend Developer building performant web applications with React, Next.js, and TypeScript. Based in New Delhi, India.",
    keywords: [
        "Aditya Kumar",
        "Frontend Developer",
        "React Developer",
        "Next.js Developer",
        "TypeScript",
        "JavaScript",
        "Web Developer",
        "India",
        "Portfolio",
        "Progressive Web App",
    ],
    authors: [{ name: "Aditya Kumar" }],
    creator: "Aditya Kumar",
    openGraph: {
        type: "website",
        locale: "en_IN",
        url: "https://adityaks-portfolio.vercel.app",
        siteName: "Aditya Kumar Portfolio",
        title: "Aditya Kumar | Frontend Developer & React Specialist",
        description:
            "Frontend Developer building performant web apps with React, Next.js, and TypeScript. Based in India.",
        // Image auto-generated by app/opengraph-image.tsx
    },
    twitter: {
        card: "summary_large_image",
        title: "Aditya Kumar | Frontend Developer & React Specialist",
        description:
            "Frontend Developer specializing in React, Next.js, and TypeScript. Based in New Delhi, India.",
        // Image auto-generated by app/opengraph-image.tsx
    },
    appleWebApp: {
        capable: true,
        statusBarStyle: "black-translucent",
        title: "Aditya Kumar",
    },
    formatDetection: {
        telephone: false,
    },
    other: {
        "mobile-web-app-capable": "yes",
    },
    robots: {
        index: true,
        follow: true,
        googleBot: {
            index: true,
            follow: true,
            "max-video-preview": -1,
            "max-image-preview": "large",
            "max-snippet": -1,
        },
    },
    alternates: {
        canonical: "https://adityaks-portfolio.vercel.app",
    },
};

export const viewport: Viewport = {
    themeColor: "#000000",
    width: "device-width",
    initialScale: 1,
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${inter.variable} ${instrumentSerif.variable} font-sans antialiased min-h-screen bg-background text-foreground`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <ClientWrapper>
                        <Navbar />
                        <main>{children}</main>
                        <Footer />
                        <ScrollToTop />
                    </ClientWrapper>
                </ThemeProvider>
                <JsonLd />
            </body>
        </html>
    );
}
